### ISSUE TITLE
Criar o Protótipo inicial

### ISSUE THREAD

**Issue by jonh-carvalho** [Projetos-de-Extensao/PFE_24.2_8002_Swap#11]

**Comment by mathjannotti** [comment]
O protótipo inicial está com o nome de protótipoBF.png em docs/assets/protótipoBF.png ou no link a seguir: https://www.figma.com/design/e6TFbuPdHvCTv3ZwiEZiWf/SWAP?node-id=0-1&t=w5OZQoviLJApRMTI-1

**Comment by mathjannotti** [comment]
troquei o protótipo de mobile para desktop
