### ISSUE TITLE
Desenvolver o Draft em código do Aplicativo de Streaming

### ISSUE THREAD

**Issue by Viniciusmendes21** [Projetos-de-Extensao/PFE_24.2_8002_Swap#13]
- [Front-End Checklist](https://frontendchecklist.io/)
- [ ]  Head
- [ ] HTML (validator html e de link)
- [ ] CSS (validator de css)
       Recomenda-se usar o plugin wave para avaliar acessiblidade

**Comment by ZaharoffG** [comment]
criei as páginas do protótipo em html e css e salvei os arquivos na pasta assets
